#kind create cluster --config kind-config.yaml
#kompose convert --out /k8s
#kubectl apply -f ./k8s/
#kind delete cluster --name mlops

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mlops
nodes:
  - role: control-plane
  #- role: control-plane
  # role: control-plane
  - role: worker
  - role: worker
  - role: worker