apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: pinot
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Bren0Miranda/big-data-on-k8s.git'
    path: repository/helm-charts/pinot
    targetRevision: master
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: datastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
