apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: filebeat
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Bren0Miranda/ws-mds-na-pratica.git'
    path: repository/helm-charts/filebeat
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
